package zxf.springboot.demo.controller;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import zxf.springboot.demo.service.model.Project;
import zxf.springboot.demo.service.model.ProjectRequest;
import zxf.springboot.demo.service.ProjectService;

import java.util.List;

/**
 * REST Controller for project management.
 */
@Slf4j
@RestController
@RequestMapping("/api/projects")
@RequiredArgsConstructor
public class ProjectController {
    private final ProjectService projectService;

    /**
     * GET /api/projects - Get all projects
     */
    @GetMapping
    public ResponseEntity<List<Project>> getAllProjects() {
        log.info("::getAllProjects");
        List<Project> projects = projectService.findAllProjects();
        return ResponseEntity.ok(projects);
    }

    /**
     * GET /api/projects/{id} - Get project by ID
     */
    @GetMapping("/{id}")
    public ResponseEntity<Project> getProjectById(@PathVariable String id) {
        log.info("::getProjectById - id: {}", id);
        Project project = projectService.queryProjectById(id);
        return ResponseEntity.ok(project);
    }

    /**
     * POST /api/projects - Create a new project
     * ID is auto-generated by the server.
     */
    @PostMapping
    public ResponseEntity<Project> createProject(@Valid @RequestBody ProjectRequest request) {
        log.info("::createProject - name: {}", request.getName());

        Project project = projectService.createProject(request.getName(), request.getDetails());
        return ResponseEntity.status(HttpStatus.CREATED).body(project);
    }

    /**
     * PUT /api/projects/{id} - Update a project
     */
    @PutMapping("/{id}")
    public ResponseEntity<Project> updateProject(@PathVariable String id, @Valid @RequestBody ProjectRequest request) {
        log.info("::updateProject - id: {}, name: {}", id, request.getName());

        Project project = projectService.updateProject(id, request.getName(), request.getDetails());
        return ResponseEntity.ok(project);
    }

    /**
     * DELETE /api/projects/{id} - Delete a project
     */
    @DeleteMapping("/{id}")
    public void deleteProject(@PathVariable String id) {
        log.info("::deleteProject - id: {}", id);
        projectService.deleteProject(id);
    }
}