package zxf.springboot.demo.controller;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import zxf.springboot.demo.model.Project;
import zxf.springboot.demo.model.ProjectRequest;
import zxf.springboot.demo.service.DatabaseService;

import java.util.List;
import java.util.Map;

/**
 * REST Controller for project management.
 */
@Slf4j
@RestController
@RequestMapping("/api/projects")
@RequiredArgsConstructor
public class ProjectController {
    private final DatabaseService databaseService;

    /**
     * GET /api/projects - Get all projects
     */
    @GetMapping
    public ResponseEntity<List<Project>> getAllProjects() {
        log.info("::getAllProjects");
        List<Project> projects = databaseService.findAllProjects();
        return ResponseEntity.ok(projects);
    }

    /**
     * GET /api/projects/{id} - Get project by ID
     */
    @GetMapping("/{id}")
    public ResponseEntity<?> getProjectById(@PathVariable String id) {
        log.info("::getProjectById - id: {}", id);
        return databaseService.queryProjectById(id)
                .<ResponseEntity<?>>map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.status(HttpStatus.NOT_FOUND)
                        .body(Map.of("error", "Project not found", "id", id)));
    }

    /**
     * POST /api/projects - Create a new project
     * ID is auto-generated by the server.
     */
    @PostMapping
    public ResponseEntity<?> createProject(@RequestBody ProjectRequest request) {
        log.info("::createProject - name: {}", request.getName());

        if (StringUtils.isBlank(request.getName())) {
            return ResponseEntity.badRequest()
                    .body(Map.of("error", "name is required"));
        }

        Project project = databaseService.createProject(request.getName());
        return ResponseEntity.status(HttpStatus.CREATED).body(project);
    }

    /**
     * PUT /api/projects/{id} - Update a project
     */
    @PutMapping("/{id}")
    public ResponseEntity<?> updateProject(@PathVariable String id, @RequestBody ProjectRequest request) {
        log.info("::updateProject - id: {}, name: {}", id, request.getName());

        if (StringUtils.isBlank(request.getName())) {
            return ResponseEntity.badRequest()
                    .body(Map.of("error", "name is required"));
        }

        return databaseService.updateProject(id, request.getName())
                .<ResponseEntity<?>>map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.status(HttpStatus.NOT_FOUND)
                        .body(Map.of("error", "Project not found", "id", id)));
    }

    /**
     * DELETE /api/projects/{id} - Delete a project
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<?> deleteProject(@PathVariable String id) {
        log.info("::deleteProject - id: {}", id);

        if (!databaseService.deleteProject(id)) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(Map.of("error", "Project not found", "id", id));
        }

        return ResponseEntity.noContent().build();
    }
}