CREATE TABLE IF NOT EXISTS project (
    id VARCHAR(40) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS task (
    id VARCHAR(40) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    project_id VARCHAR(40),
    priority INT DEFAULT 0
);