package zxf.springboot.demo.apitest;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.skyscreamer.jsonassert.comparator.JSONComparator;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.wiremock.spring.ConfigureWireMock;
import org.wiremock.spring.EnableWireMock;
import zxf.springboot.demo.apitest.support.BaseApiTest;
import zxf.springboot.demo.apitest.support.json.JSONComparatorFactory;
import zxf.springboot.demo.apitest.support.json.JsonLoader;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Project API Tests.
 *
 * Features:
 * - Uses WireMock to mock external services
 * - Uses H2 in-memory database
 * - Uses TestRestTemplate for HTTP calls
 * - Uses JSONAssert for response validation
 * - Each test method tests only ONE endpoint
 * - Project ID is auto-generated by server
 */
@EnableWireMock({
    @ConfigureWireMock(name = "task-service", port = 8090)
})
public class ProjectApiTests extends BaseApiTest {
    private JSONComparator projectApiJsonResponseComparator;

    @BeforeEach
    void setupForEach() {
        projectApiJsonResponseComparator = JSONComparatorFactory.buildApiResponseComparator();
    }

    // ==================== POST /api/projects Tests ====================

    @Test
    void testCreateProject() throws Exception {
        // Given
        String projectName = "New Project";
        String url = "/api/projects";
        String requestBody = JsonLoader.load("project/post/request.json",
                Map.of("name", projectName));
        int initialCount = databaseVerifier.countProjects();

        // When
        ResponseEntity<String> response = httpPostAndAssert(url, commonHeadersAndJson(), requestBody, String.class, HttpStatus.CREATED, MediaType.APPLICATION_JSON);

        // Then
        String expectedJson = JsonLoader.load("project/post/created.json", Map.of("name", projectName));
        JSONAssert.assertEquals(expectedJson, response.getBody(), projectApiJsonResponseComparator);

        // And - verify database state
        assertThat(databaseVerifier.countProjects()).isEqualTo(initialCount + 1);
        String createdProjectId = databaseVerifier.findProjectIdByName(projectName);
        assertThat(createdProjectId).isNotNull();
        assertThat(databaseVerifier.getProjectName(createdProjectId)).isEqualTo(projectName);
    }

    @Test
    void testCreateProjectWithValidationError() throws Exception {
        // Given
        String url = "/api/projects";
        String requestBody = JsonLoader.load("project/post/request.json",
                Map.of("name", ""));

        // When
        ResponseEntity<String> response = httpPostAndAssert(url, commonHeadersAndJson(), requestBody, String.class, HttpStatus.BAD_REQUEST, MediaType.APPLICATION_JSON);

        // Then
        String expectedJson = JsonLoader.load("project/post/validation-error.json");
        JSONAssert.assertEquals(expectedJson, response.getBody(), projectApiJsonResponseComparator);
    }

    // ==================== GET /api/projects/{id} Tests ====================

    @Test
    void testGetProjectById() throws Exception {
        // Given - 使用预置数据 proj-001
        String url = "/api/projects/proj-001";

        // When
        ResponseEntity<String> response = httpGetAndAssert(url, commonHeaders(), String.class, HttpStatus.OK, MediaType.APPLICATION_JSON);

        // Then
        String expectedJson = JsonLoader.load("project/get-by-id/ok.json");
        JSONAssert.assertEquals(expectedJson, response.getBody(), projectApiJsonResponseComparator);
    }

    @Test
    void testGetProjectByIdNotFound() throws Exception {
        // Given
        String url = "/api/projects/non-existent-id";

        // When
        ResponseEntity<String> response = httpGetAndAssert(url, commonHeaders(), String.class, HttpStatus.NOT_FOUND, MediaType.APPLICATION_JSON);

        // Then
        String expectedJson = JsonLoader.load("project/get-by-id/not-found.json");
        JSONAssert.assertEquals(expectedJson, response.getBody(), projectApiJsonResponseComparator);
    }

    // ==================== GET /api/projects Tests ====================

    @Test
    void testGetAllProjects() throws Exception {
        // Given - 使用预置数据
        String url = "/api/projects";

        // When
        ResponseEntity<String> response = httpGetAndAssert(url, commonHeaders(), String.class, HttpStatus.OK, MediaType.APPLICATION_JSON);

        // Then
        String expectedJson = JsonLoader.load("project/get-all/ok.json");
        JSONAssert.assertEquals(expectedJson, response.getBody(), projectApiJsonResponseComparator);
    }

    // ==================== PUT /api/projects/{id} Tests ====================

    @Test
    void testUpdateProject() throws Exception {
        // Given - 使用预置数据 proj-001
        String projectId = "proj-001";
        String url = "/api/projects/" + projectId;
        String newName = "Updated Project Name";
        String requestBody = JsonLoader.load("project/put/request.json",
                Map.of("name", newName));

        // When
        ResponseEntity<String> response = httpPutAndAssert(url, commonHeadersAndJson(), requestBody, String.class, HttpStatus.OK, MediaType.APPLICATION_JSON);

        // Then
        String expectedJson = JsonLoader.load("project/put/ok.json");
        JSONAssert.assertEquals(expectedJson, response.getBody(), projectApiJsonResponseComparator);

        // And - verify database state
        assertThat(databaseVerifier.getProjectName(projectId)).isEqualTo(newName);
    }

    @Test
    void testUpdateProjectNotFound() throws Exception {
        // Given
        String url = "/api/projects/non-existent-id";
        String requestBody = JsonLoader.load("project/put/request.json",
                Map.of("name", "Updated Name"));

        // When
        ResponseEntity<String> response = httpPutAndAssert(url, commonHeadersAndJson(), requestBody, String.class, HttpStatus.NOT_FOUND, MediaType.APPLICATION_JSON);

        // Then
        String expectedJson = JsonLoader.load("project/put/not-found.json");
        JSONAssert.assertEquals(expectedJson, response.getBody(), projectApiJsonResponseComparator);
    }

    @Test
    void testUpdateProjectValidationError() throws Exception {
        // Given
        String url = "/api/projects/proj-001";
        String requestBody = JsonLoader.load("project/put/request.json",
                Map.of("name", ""));

        // When
        ResponseEntity<String> response = httpPutAndAssert(url, commonHeadersAndJson(), requestBody, String.class, HttpStatus.BAD_REQUEST, MediaType.APPLICATION_JSON);

        // Then
        String expectedJson = JsonLoader.load("project/put/validation-error.json");
        JSONAssert.assertEquals(expectedJson, response.getBody(), projectApiJsonResponseComparator);
    }

    // ==================== DELETE /api/projects/{id} Tests ====================

    @Test
    @Sql(scripts = "classpath:sql/cases/project-p-test.sql")
    void testGetProjectById_WithCaseLevelSql() throws Exception {
        // Given - 使用 case-level SQL 创建的测试数据
        String projectId = "p-test";
        String url = "/api/projects/" + projectId;

        // When
        ResponseEntity<String> response = httpGetAndAssert(url, commonHeaders(), String.class, HttpStatus.OK, MediaType.APPLICATION_JSON);

        // Then
        assertThat(response.getBody()).contains("Case Test Project");
        assertThat(databaseVerifier.getProjectName(projectId)).isEqualTo("Case Test Project");
    }

    @Test
    void testDeleteProject() throws Exception {
        // Given - 使用预置数据 proj-delete
        String projectId = "proj-delete";
        String url = "/api/projects/" + projectId;
        int initialCount = databaseVerifier.countProjects();
        assertThat(databaseVerifier.projectExists(projectId)).isTrue();

        // When & Then
        httpDeleteAndAssert(url, commonHeaders(), String.class, HttpStatus.NO_CONTENT, null);

        // And - verify database state
        assertThat(databaseVerifier.projectExists(projectId)).isFalse();
        assertThat(databaseVerifier.countProjects()).isEqualTo(initialCount - 1);
    }

    @Test
    void testDeleteProjectNotFound() throws Exception {
        // Given
        String url = "/api/projects/non-existent-id";

        // When & Then
        httpDeleteAndAssert(url, commonHeaders(), String.class, HttpStatus.NOT_FOUND, MediaType.APPLICATION_JSON);
    }
}